from __future__ import annotations

from typing import Protocol, Iterable
from .domain import Input, RawRecord, CanonicalDocument, SearchHit, ACL, AuditEvent


class Connector(Protocol):
    name: str
    def read(self) -> Iterable[Input]: ...


class Canonicalizer(Protocol):
    def canonicalize(self, record: RawRecord, acl: ACL) -> CanonicalDocument: ...


class DocumentStore(Protocol):
    def put(self, document: CanonicalDocument) -> None: ...
    def get(self, document_id: str) -> CanonicalDocument | None: ...
    def all(self) -> Iterable[CanonicalDocument]: ...
    def tombstone(self, document_id: str) -> None: ...
    def purge(self, before: object) -> int: ...


class SearchIndex(Protocol):
    def replace(self, document: CanonicalDocument) -> None: ...
    def remove(self, document_id: str) -> None: ...
    def search(self, query: str) -> Iterable[SearchHit]: ...


class IdentityACL(Protocol):
    def resolve(self, record: RawRecord) -> ACL: ...


class AuditStore(Protocol):
    def append(self, event: AuditEvent) -> None: ...
    def all(self) -> Iterable[AuditEvent]: ...
